languageCode: "en-us"
contentdir: "content"
publishdir: "public"
builddrafts: false
baseurl: "http://tstra.us"
theme: "theme"
canonifyurls: true
title: "tstraus"
author: "Tucker Strausbaugh"
copyright: "be nice"


indexes:
   category: "categories"
   tag: "tags"

params:
  AuthorName: "Tucker"
  github: "https://github.com/tstraus"
  facebook: "https://www.facebook.com/tckrsstrsbgh"
  email: "strausbaugh.tucker@gmail.com"
  description: "Tucker Strausbaugh"
  cv: "/pages/cv"
  legalnotice: "/pages/legal-notice"
  linkedin: "https://www.linkedin.com/in/tucker-strausbaugh-04018027"
  cover: "/images/background-cover.jpg"
  logo: "/img/logo-1.jpg"
  links:
    About: "/about/home"
    Resume: "/resume/home"
    Drawings: "/drawings/"
    Code: "/code/"
    Misc: "/misc/"
  ProfilePicture: "/images/tuckles.jpg"
  enableLandingPage: true
  landingPageRedirectUrl: "/about/home"
